service: interference
runtime: nodejs16

handlers:
  - url: /
    secure: always
    static_files: dist/webgl-test/index.html
    upload: dist/webgl-test/index.html

  #  Routing rules for resources, css, js, images etc. Any file with format filename.ext
  - url: /(.*\.(.+))$
    secure: always
    static_files: dist/webgl-test/\1
    upload: dist/webgl-test/(.*\.(.+))$

  #  Routing rule for Angular Routing
  - url: /(.*)
    secure: always
    static_files: dist/webgl-test/index.html
    upload: dist/webgl-test/index.html